version: "3.0"
services:
  client1:
    image: docker.pkg.github.com/jointfaas/storage-center/client:latest
    cap_add:
    - NET_ADMIN
    command: ['-H', 'client2', -r, 'server:50000']
  client2:
    image: docker.pkg.github.com/jointfaas/storage-center/client:latest
    cap_add:
    - NET_ADMIN
    command: ['-H', 'client2', -r, 'server:50000']
  server:
    image: docker.pkg.github.com/jointfaas/storage-center/server:latest
    cap_add:
    - NET_ADMIN
  benchmark:
    image: docker.pkg.github.com/jointfaas/storage-center/tester:latest
    entrypoint: ['/bin/sh', '-c', 'sleep 3600']